### PR TITLE
Fix typo on the README.md

### PR DESCRIPTION
**Pull request by EsteveAguilera**

### CODE REVIEW

**Review by Sloy — APPROVED** [review]
Thanks

**Comment by EsteveAguilera** [comment]
Ooops, it seems there's something wrong with Travis...

`ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-7-oracle`
`Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.`

**Comment by Sloy** [comment]
Let's rebuild after https://github.com/SchibstedSpain/Parallax-Layer-Layout/pull/20

**Comment by EsteveAguilera** [comment]
@Sloy we're on green now! 🕺

**Comment by Sloy** [comment]
Sorry forgot about it 👍

**Pull request merged**
